# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 643460f186afc80a9dbc402899f0dd9713c57a28a9c609c40ce32627cd59f26b4a90307a5596bfd8750758d3651be019c2d369c3086f34fbc47186cef0d36a4a

test:
  secret_key_base: 669187a08deabbaa479bfd8988839016bfeab159e911823ab24e27b57e7d50ee0f93edf3a452f9a72043dd630769f34161f15e3f6339bd8cb37784c1648a53ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
